### ISSUE TITLE
[doc] Issue in "MIRRORING THE SUSE LIBERTY LINUX LTSS REPOSITORIES WITH RMT"

### ISSUE THREAD

**Issue by gusraggio** [SUSE/doc-liberty#31] opened 2024-10-15 11:33 UTC
MIRRORING THE SUSE LIBERTY LINUX LTSS REPOSITORIES WITH RMT:

https://documentation.suse.com/liberty/7/single-html/lite-quickstart/#pro-mirror-repositories-with-rmt

Please review case: https://scc.suse.com/support/cases/01552823

Basically: 

- Mirror product id 1251
- Enable the repo mentioned,

$/sosreport-lc6mk101-2024-09-12-perxrch> cat etc/yum.repos.d/SUSE_Liberty_Linux_LTSS_x86_64\:RES-7-BASE-Updates.repo
[SUSE_Liberty_Linux_LTSS_x86_64:RES-7-BASE-Updates]
name=RES-7-BASE-Updates
enabled=0
autorefresh=1
baseurl=https://10.201.167.12/repo/SUSE/Updates/RES-BASE/7/x86_64/update/
service=SUSE_Liberty_Linux_LTSS_x86_64

- The actual repo synced in RMT is https://10.201.167.12/repo/SUSE/Updates/RES/7/x86_64/update/ (without the -BASE)

**Comment by tahliar** [comment] 2024-10-15 23:50
Hi, I can't access that support case. What needs to be fixed in the doc? 

Product ID 1251 is for the old non-LTSS repos. The LTSS repos are under product ID 2702.

**Comment by gusraggio** [comment] 2024-10-16 06:13
LTSS repos only bring updates released after EOL. After syncing only LTSS repos and upgradeing the entire system the system was not able to boot. Sync of the product id 1251 allowed the system to boot properly.

**Comment by tahliar** [comment] 2024-10-16 06:36
Does it work if you have both `RES-7-LTSS-Updates` and `RES-7-BASE-Updates` enabled, both in RMT and on the registered system? I can see now that `BASE-Updates` isn't enabled by default when you enable product 2702 (only `LTSS-Updates` is). If it doesn't work with both of those enabled, then this might be a bug rather than a doc issue. 

AFAIK it's no longer supported to register new systems with 1251, so I don't think I can add that product back into the doc.

**Comment by tahliar** [comment] 2024-10-18 07:25
I've installed a couple of new CentOS 7 systems and was able to register, update, and reboot them following the instructions in the doc, so I'm closing this issue as I can't reproduce it. 

However, I was inspired to add some additional info, so I opened PR #32.

**Closed by tahliar** 2024-10-18 07:25 UTC
